# winget (id, name)
$azure = @(
  [tuple]::Create("Azure.AzureCLI", "Azure CLI")
  [tuple]::Create("Azure.AzurePowerShell", "Azure PowerShell")
  [tuple]::Create("Azure.AzureStorageExplorer", "Azure Storage Explorer")
  [tuple]::Create("Azure.CLI", "Azure CLI")
  [tuple]::Create("Azure.CloudShell", "Azure Cloud Shell")
  [tuple]::Create("Azure.DataStudio", "Azure Data Studio")
  [tuple]::Create("Azure.IoTCentral", "Azure IoT Central")
  [tuple]::Create("Azure.PowerShell", "Azure PowerShell")
  [tuple]::Create("Azure.StorageExplorer", "Azure Storage Explorer")
  [tuple]::Create("Azure.VSCode", "Azure Tools for Visual Studio Code")
)
$dev = @(
  [tuple]::Create("Docker.DockerDesktop", "Docker Desktop")
  [tuple]::Create("Microsoft.WindowsTerminal", "Windows Terminal")
  [tuple]::Create("Microsoft.PowerShell", "PowerShell")
  [tuple]::Create("Microsoft.WinDbg", "WinDbg")
  [tuple]::Create("Microsoft.DevHome", "DevHome")
  [tuple]::Create("Git.Git", "Git")
  [tuple]::Create("Fork.Fork", "Git Fork")
  [tuple]::Create("GitHub.GitHubDesktop", "GitHub Desktop")
  [tuple]::Create("Postman.Postman", "Postman")
  [tuple]::Create("Unity.UnityHub", "Unity Hub")
  [tuple]::Create("JetBrains.Toolbox", "JetBrains")
  [tuple]::Create("Ollama.Ollama", "Ollama")
  [tuple]::Create("ElementLabs.LMStudio", "LM Studio")
  [tuple]::Create("Microsoft.DotNet.SDK.Preview", ".NET Preview")
  [tuple]::Create("Microsoft.DotNet.SDK.8", ".NET 8")
  [tuple]::Create("CoreyButler.NVMforWindows", "nvm")
  [tuple]::Create("DenoLand.Deno", "Deno")
  [tuple]::Create("Oven-sh.Bun", "Bun")
  [tuple]::Create("GoLang.Go", "Go")
  [tuple]::Create("GolangCI.golangci-lint", "golangci-lint")
  [tuple]::Create("zig.zig", "Zig")
  [tuple]::Create("Rustlang.Rustup", "Rustup")
)
$visualstudio = @(
  [tuple]::Create("Microsoft.VisualStudioCode", "Visual Studio Code")
  [tuple]::Create("VisualStudio.VisualStudio2022Community", "Visual Studio 2022 Community")
)
$desktop = @(
  [tuple]::Create("NZXT.CAM", "NZXT")
)
$accessories = @(
  [tuple]::Create("Logitech.GHUB", "GHUB")
  [tuple]::Create("Logitech.OptionsPlus", "Logitech Options")
)
$optionalServices = @(
  [tuple]::Create("Bitwarden.Bitwarden", "Bitwarden")
  [tuple]::Create("Bitwarden.CLI", "BitwardenCLI")
  [tuple]::Create("EpicGames.EpicGamesLauncher", "Epic Games Launcher")
  [tuple]::Create("Microsoft.Teams", "Teams")
  [tuple]::Create("Mozilla.Thunderbird", "Thunderbird")
  [tuple]::Create("OpenWhisperSystems.Signal", "Signal")
  [tuple]::Create("Plex.Plexamp", "Plexamp")
  [tuple]::Create("SlackTechnologies.Slack", "Slack")
  [tuple]::Create("tailscale.tailscale", "tailscale")
  [tuple]::Create("Vysor.Vysor", "Vysor")
)