#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'status'
style = 'plain'
template = '{{ if gt .Code 0 }}<#ff0000></>{{ else }}<#23d18b></>{{ end }} '

[blocks.segments.properties]
always_enabled = true

[[blocks.segments]]
type = 'executiontime'
style = 'plain'
foreground = '#bab02a'
template = 'took  {{ .FormattedMs }} '

[blocks.segments.properties]
threshold = 10.0

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'os'
style = 'plain'
foreground = '#26C6DA'
template = '{{ if .WSL }}WSL at {{ end }}{{.Icon}} '

[[blocks.segments]]
type = 'session'
style = 'diamond'
foreground = '#26C6DA'
template = ' {{ .UserName }}@{{ .HostName }} '

[[blocks.segments]]
type = 'git'
style = 'plain'
foreground = '#FFE700'
foreground_templates = [
  '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}',
  '{{ if gt .Ahead 0 }}#16c60c{{ end }}',
  '{{ if gt .Behind 0 }}#f450de{{ end }}',
]
template = '{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

[blocks.segments.properties]
fetch_status = true
fetch_upstream_icon = true

[[blocks]]
type = 'prompt'
alignment = 'right'

[[blocks.segments]]
type = "dotnet"
style = "plain"
foreground = "#00ffff"
template = "  {{ .Full }} "

[[blocks.segments]]
type = 'go'
style = 'plain'
foreground = 'blue'
template = ' {{ .Full }} '

[[blocks.segments]]
type = 'python'
style = 'diamond'
background = '#3776ab'
foreground = '#ffd343'
leading_diamond = ''
trailing_diamond = ''
template = '  ({{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Major }}.{{ .Minor }}{{ end }}) '

[[blocks.segments]]
type = 'node'
style = 'diamond'
foreground = '#ffffff'
background = '#6CA35E'
leading_diamond = ''
trailing_diamond = ''
template = '  {{ .Full }} '

[[blocks.segments]]
type = 'java'
style = 'diamond'
foreground = '#ffffff'
background = '#4c1f5e'
leading_diamond = ' '
trailing_diamond = ''
template = '  {{ .Full }} '

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'path'
style = 'plain'
foreground = '#77E4F7'
template = '{{ .Path }} '

[blocks.segments.properties]
style = 'full'

[[blocks.segments]]
type = 'text'
style = 'plain'
foreground = '#43D426'
template = '❯ '

[transient_prompt]
background = 'transparent'
foreground = 'magenta'
template = '{{ now | date "15:04:05" }} ❯ '
