#! /bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/common.sh"

NVIM_SRC="$STOW_DIR/nvim/.config/nvim"
GEN_FILE="$NVIM_SRC/lua/sauce/generated.lua"
SKIP_BOOTSTRAP="${SKIP_NVIM_BOOTSTRAP:-0}"

if ! command -v nvim >/dev/null 2>&1; then
    log_install "Neovim not found; installing..."
    install_pkgs neovim || { log_error "Could not install neovim."; exit 1; }
fi
if ! command -v git >/dev/null 2>&1; then
    log_error "git is required to bootstrap lazy.nvim."
    exit 1
fi

declare -a SERVERS=()
declare -a PARSERS=()
add() { SERVERS+=("$1"); shift; PARSERS+=("$@"); }

command -v go      >/dev/null 2>&1 && add gopls go gomod gosum
command -v python3 >/dev/null 2>&1 && add pyright python
command -v ruff    >/dev/null 2>&1 && SERVERS+=(ruff)
command -v node    >/dev/null 2>&1 && add ts_ls typescript javascript tsx
command -v dotnet  >/dev/null 2>&1 && add omnisharp c_sharp
{ command -v cargo || command -v rustc; } >/dev/null 2>&1 && add rust_analyzer rust
command -v gcc     >/dev/null 2>&1 && add clangd c cpp
command -v docker  >/dev/null 2>&1 && add dockerls dockerfile

lua_list() { local x; for x in "$@"; do printf '    "%s",\n' "$x"; done; }
ensure_dir "$(dirname "$GEN_FILE")"
{
    echo "-- AUTO-GENERATED by build-nvim.sh -- do not edit; do not commit."
    echo "-- Reflects language toolchains detected on this machine."
    echo "return {"
    echo "  servers = {"
    [ "${#SERVERS[@]}" -gt 0 ] && lua_list "${SERVERS[@]}"
    echo "  },"
    echo "  parsers = {"
    [ "${#PARSERS[@]}" -gt 0 ] && lua_list "${PARSERS[@]}"
    echo "  },"
    echo "}"
} > "$GEN_FILE"
log_link "Generated $GEN_FILE (${#SERVERS[@]} extra server(s), ${#PARSERS[@]} extra parser(s))."

stow_pkg nvim

profile_register nvim <<'EOF'
# Neovim
export EDITOR="nvim"
export VISUAL="nvim"
alias vi="nvim"
alias vim="nvim"
EOF

if [ "$SKIP_BOOTSTRAP" = "1" ]; then
    log_info "SKIP_NVIM_BOOTSTRAP=1 -- skipping plugin/server sync."
else
    log_install "Syncing plugins (lazy.nvim)..."
    nvim --headless "+Lazy! sync" +qa 2>&1 || log_warn "Lazy sync returned non-zero (often benign)."

    log_install "Installing treesitter parsers..."
    nvim --headless "+Lazy! load nvim-treesitter" \
        "+lua vim.cmd('TSInstallSync '..table.concat(require('sauce.toolset').parsers,' '))" +qa 2>&1 \
        || log_warn "Treesitter parser install returned non-zero."

    log_install "Installing LSP servers via Mason (may take a few minutes)..."
    nvim --headless "+Lazy! load nvim-lspconfig" \
        "+lua local done=false; vim.api.nvim_create_autocmd('User',{pattern='MasonToolsUpdateCompleted',callback=function() done=true end}); pcall(vim.cmd,'MasonToolsInstall'); vim.wait(240000,function() return done end,500)" \
        +qa 2>&1 || log_warn "Mason install returned non-zero; run :Mason in nvim to finish."
fi

log_done "Neovim config built."
log_hint "Open a .go/.py/.ts file, then run :Lazy, :Mason, :LspInfo, :checkhealth to verify."
