#! /bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/common.sh"

PLUGINS=(
    "zsh-autosuggestions|https://github.com/zsh-users/zsh-autosuggestions"
    "zsh-syntax-highlighting|https://github.com/zsh-users/zsh-syntax-highlighting"
)

cleanup() {
    log_clean "Removing zsh plugins..."
    local entry name
    for entry in "${PLUGINS[@]}"; do
        name=${entry%%|*}
        remove_paths "$ZSH_PLUGINS/$name"
    done
    remove_paths "$ZSH_PLUGINS/plugins.zsh"
    log_done "zsh plugins removed."
}
dispatch_remove "$@"

ensure_dir "$ZSH_PLUGINS"
for entry in "${PLUGINS[@]}"; do
    name=${entry%%|*}; url=${entry#*|}
    dest="$ZSH_PLUGINS/$name"
    if [ -d "$dest/.git" ]; then
        echo "🔄 Updating $name..."
        git -C "$dest" pull --ff-only
    else
        log_download "Cloning $name..."
        git clone --depth 1 "$url" "$dest"
    fi
done

LOADER="$ZSH_PLUGINS/plugins.zsh"
log_link "Writing plugin loader -> $LOADER"
{
    echo "# Generated by update-zsh-plugins.sh — do not edit."
    echo "# Sources zsh plugins in order; zsh-syntax-highlighting is emitted last."
    for entry in "${PLUGINS[@]}"; do
        name=${entry%%|*}
        cat <<EOF

# $name
for _p in \\
    /usr/share/$name/$name.zsh \\
    /usr/share/zsh/plugins/$name/$name.zsh \\
    "\$HOME/.zsh/$name/$name.zsh"; do
    [ -f "\$_p" ] && source "\$_p" && break
done
EOF
    done
    echo
    echo "unset _p"
} > "$LOADER"

log_done
log_hint "Restart your shell or run 'source ~/.zshrc' to load the plugins."
